### ISSUE TITLE
cannot export profile

### ISSUE THREAD

**Issue by pompobit** [genderquery/netflix-migrate#16]
Hi,

I'm trying to export a profile with the command:

`netflix-migrate --email xxxxxx@gmail.com --profile yyyyyyy --export ratings.json`

I'm prompted to insert the password, I type it and I get:

`HttpError { name: 'HttpError', message: '401: Unauthorized' }`

I cloned the repository just now and installed with `sudo npm install -g netflix-migrate`, the installation seems to succeed.

Any idea?

**Comment by pennstatephil** [comment]
same issue. you're probably right @LBBO 😭

**Comment by LBBO** [comment]
I found the issue: Netflix changed the name of the email input field of their login form. Should be working again in a short while!

**Comment by 0vermind** [comment]
Hi, l get the issue described HttpError { name: 'HttpError', message: '403: Forbidden' } when I try to export.
I've used successfully netflix-migrate before. 
Now I get the error above. As something changed on the Netflix side? Anyone else has this problem?

**Comment by LBBO** [comment]
I just tried executing the script and it worked just fine. Since you have already used netflix-migrate before, have you tried updating the package?

**Comment by 0vermind** [comment]
Hi @LBBO, thanks for the response.
I've just `git clone `it again and I did a `npm install `again.
I also tried on a linux machine (I'm on windows) and on different accounts.
Same error above:
`HttpError { name: 'HttpError', message: '403: Forbidden' }`

I also updated all dependencies with ncu -u

right now my pakage.json is:
`  "name": "netflix-migrate",
  "version": "0.3.0",
  "description": "A command-line tool to migrate data to and from Netflix profiles",
  "keywords": [
    "netflix",
    "migrate"
  ],
  "license": "MIT",
  "author": "Avery Larsen <avery@stoatly.com>",
  "homepage": "https://github.com/genderquery/netflix-migrate",
  "repository": {
    "type": "git",
    "url": "https://github.com/genderquery/netflix-migrate.git"
  },
  "main": "./index.js",
  "bin": {
    "netflix-migrate": "./index.js"
  },
  "scripts": {
    "test": "nyc --reporter=text --check-coverage --lines 100 mocha main.test.js",
    "test-without-coverage": "mocha main.test.js"
  },
  "dependencies": {
    "array.prototype.find": "^2.0.0",
    "async": "^2.0.0-rc.5",
    "commander": "^2.9.0",
    "netflix2": "0.1.1",
    "prompt": "^1.0.0"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "eslint": "^5.13.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "mocha": "^5.2.0",
    "nyc": "^13.0.1",
    "sinon": "^7.2.3",
    "sinon-chai": "^3.2.0"
  }
}

ie. On Linux I do
`node index.js` and everything seems working as expected asking email password and profile.
