### ISSUE TITLE
Cannot read property 'serverDefs' of undefined

### ISSUE THREAD

**Issue by derelk** [genderquery/netflix-migrate#2]
Really excited to use this, thanks for writing it. Unfortunately I'm unable to get it to run—getting this error from netflix2. So far I'm not sure if the problem is actually in netflix-migrate or netflix2. I tried running netflix-migrate with netflix2@0.0.2 instead of 0.0.1, but the error is the same. I will keep digging but I have fairly limited Node & JS skills.

```
/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:46
    self.apiRoot = contextData.serverDefs.data.SHAKTI_API_ROOT
                              ^

TypeError: Cannot read property 'serverDefs' of undefined
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:46:31
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/async/dist/async.js:356:16
    at nextTask (/usr/local/lib/node_modules/netflix-migrate/node_modules/async/dist/async.js:5057:29)
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/async/dist/async.js:5064:13
    at apply (/usr/local/lib/node_modules/netflix-migrate/node_modules/async/dist/async.js:21:25)
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/async/dist/async.js:56:12
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/async/dist/async.js:840:16
    at Request._callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:239:5)
    at Request.self.callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
```

**Comment by MrDocx** [comment]
I have the same issue :'(

**Comment by gnjack** [comment]
Looks like an issue with genderquery/node-netflix2 - the Netflix 'shakti' API and Netflix client side javascript structure has changed and netflix2 needs updating.

For example:
`https://www.netflix.com/api/shakti/ratingHistory/8347ed8da8353156064c4dfcc92232af72ba983a?pg=0`
has changed to
`https://www.netflix.com/api/shakti/0feb190f/ratinghistory?pg=0`

`context.netflix.contextData.serverDefs.data.SHAKTI_API_ROOT`
has changed to
`context.netflix.reactContext.models.serverDefs.data.SHAKTI_API_ROOT`

I've managed to hack a working local copy together, I'll see if I can fork genderquery/node-netflix2 and submit a PR at some point.

**Comment by genderquery** [comment]
Sorry for neglecting this project. I'm working on the issue now. @gnjack is correct, the Netflix has changed some things around. I'm working on the issue now, but if anyone beats me to it, I would be more than happy to accept any pull requests.

**Comment by genderquery** [comment]
Updated packages on npm and changed the netflix2 dependency version. Thank you, everyone, for contributing!
