### ISSUE TITLE
TypeError: Cannot read property 'models' of undefined

### ISSUE THREAD

**Issue by sanok** [genderquery/netflix-migrate#24]
When exporting an old Netflix profile. Version 3.0

C:\Users\XXXX\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:394
    self.netflixContext = context.netflix.reactContext.models
                                                       ^

TypeError: Cannot read property 'models' of undefined
    at Request._callback (C:\Users\XXXX\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:394:56)
    at Request.self.callback (C:\Users\XXXX\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\XXXX\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Gunzip.<anonymous> (C:\Users\XXXX\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at Gunzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by LBBO** [comment]
I tried to reproduce this problem with a fresh installation but everything worked as expected. Did you verify that all your login data was correct? If so, could you give me more context such as the exact command you entered (minus your personal data, of course)?

**Comment by sanok** [comment]
Hi Michael.

You can test with my real account

Mail marlop.sergio@gmail.com
Secret 123456

Thank you in advance, Sergio

**Comment by LBBO** [comment]
Hey Sergio,

Thanks for trusting me with your account! However, you should probably not send anyone your login data via a GitHub issue, but rather in a private message. I took the liberty of deleting the sensitive information in your comment (after writing it down, of course) and I'll let you know, as soon as I no longer need your account. Since I am rather busy at the moment, I won't be able to look into this issue until this weekend, though.

**Comment by sanok** [comment]
Hi michael

Thanks for taking your time

Sincerely I supposed that replying to email will not publish data on
github... thanks for keeping private.

Kind regarfs, Sergio

**Comment by LBBO** [comment]
Hey Sergio!

Good news: I was able to reproduce and fix your issue with your account. The problem occured during login and the only meaningful difference between our two accounts seems to be that yours is inactive and mine isn't.

The fix isn't great, but it works. You should be able to just update netflix-migrate to v0.3.1 and run the script without any problems. If you do run into any trouble, please let me know!

Also, I have deleted all your data from my computer and you should probably change your password again.

¡Muchos saludos de Alemania!
Michael

**Comment by sanok** [comment]
Thank you very much Michael! The new version et me to export my Netflix
history from my old account. Password updated ;)

But now, trying to import on my new account it gives me a new error.

netflix-migrate --email new_email@address.com --profile XXXX --import
netflixData_just_exported.json
Password:
HttpError { name: 'HttpError', message: '401: Unauthorized' }
Error: Could not set rating for undefined. For more information, please see
previous log statements.
    at
C:\XXXXXX\AppData\Roaming\npm\node_modules\netflix-migrate\main.js:250:10
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

How can I help you to debug this?

Thanks in advance, Sergio.

**Comment by LBBO** [comment]
Hey Sergio,

I'm sorry to hear that! As this is a separate problem, I've opened a new issue to discuss it and I'll look into it right now.
