### ISSUE TITLE
HttpError { name: 'HttpError', message: '401: Unauthorized' }

### ISSUE THREAD

**Issue by LBBO** [genderquery/netflix-migrate#26]
There have been reports of the following error while importing data:

```
HttpError { name: 'HttpError', message: '401: Unauthorized' }
Error: Could not set rating for undefined. For more information, please see previous log statements.
    at /home/USER/.nvm/versions/node/v9.3.0/lib/node_modules/netflix-migrate/main.js:250:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

The `set rating for undefined` part was a typo, undefined should actually be the title of the rating. However, that makes no difference, as this error seems to occur whilst setting the very first rating of the list, no matter the movie's name or rating.

**Comment by LBBO** [comment]
This issue was mentioned in the comments of #22 and #24.

**Comment by Stanzilla** [comment]
Anything I can do to help debug it? I can indeed confirm that it happens for the very first item in the list, if I drop it, it just happens for the first again.

**Comment by LBBO** [comment]
I'm not sure yet, I just started looking into it. So far, I have confirmed that it also happens with the old star type ratings so my assumption is that netflix changed their API again. Hopefully, this change won't be too hard to adapt to. Thanks for your offer though, I'll let you know when I found something you can help with!

**Comment by LBBO** [comment]
So I think I found the problem: netflix creates an authURL for every session after a successful login and it looks like they removed it from where it used to be. I found the same authURL in another location and using that authURL I was able to import my ratings to netflix.

If you'd like to, you could verify this by replacing `node_modules/netflix2/lib/netflix2.js:404` which should be ```self.authUrls[url] = context.netflix.reactContext.authURL``` with ```self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL```.

I'd also like to mention that this fix won't work with inactive accounts, as I don't own an inactive account at the moment and am not able to find out where the authURL is stored there.

**Comment by Stanzilla** [comment]
That gives

```
HttpError { name: 'HttpError', message: '401: Unauthorized' }
Error: Could not set rating for undefined. For more information, please see previous log statements.
    at C:\Users\Benjamin\AppData\Local\scoop\persist\nodejs\bin\node_modules\netflix-migrate\main.js:250:10
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

but the line numbers don't match up, do you have any other changes in `netflix2.js`?

**Comment by LBBO** [comment]
Oh right, I had added that line a few minutes before changing it and forgot all about it. However, you might not have the up-to-date version (0.3.1). If you do, make your `Netflix.prototype.__getContextData` function (line `362`) look like this:

```javascript
Netflix.prototype.__getContextData = function (url, callback) {
  var self = this
  var options = {
    url: url,
    method: 'GET',
    followAllRedirects: true
  }
  this.__request(options, function (error, response, body) {
    if (error) {
      return callback(error)
    }
    if (response.statusCode !== 200) {
      return callback(
        new HttpError(response.statusCode, response.statusMessage)
      )
    }
    var context = {
      window: {},
      netflix: {}
    }
    vm.createContext(context)
    var $ = cheerio.load(body)
    $('script').map(function (index, element) {
      // don't run external scripts
      if (!element.attribs.src) {
        var script = $(element).text()
        if (script.indexOf('window.netflix') === 0) {
          vm.runInContext(script, context)
        }
      }
    })
    /*
     * For some reason, context.netflix.reactContext does not always exist. The cause may be wether an account is active
     * or not, but that is not for sure.
     *
     * Currently, this fixes the issue, as the shakti API root seems to always be identical and endpointIdentifiers
     * seem to always be an empty object. This is a quick and dirty fix due to lack of more information!
     */
    if (context.netflix.reactContext) {
      self.netflixContext = context.netflix.reactContext.models
      self.apiRoot = self.netflixContext.serverDefs.data.SHAKTI_API_ROOT + '/' + self.netflixContext.serverDefs.data.BUILD_IDENTIFIER
      self.endpointIdentifiers = self.netflixContext.serverDefs.data.endpointIdentifiers
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
    } else if (context.netflix.contextData) {
      self.netflixContext = context.netflix.contextData
      self.apiRoot = 'https://www.netflix.com/api/shakti/' + context.netflix.contextData.serverDefs.BUILD_IDENTIFIER
      self.endpointIdentifiers = {}
      self.authUrls[url] = context.netflix.contextData.authURL
    } else {
      throw new Error(
        'An error occurred that appears to be similar to ' +
        'https://github.com/genderquery/netflix-migrate/issues/24 !'
      )
    }

    callback(null)
  })
}
```

The only change should be the addition of the line before the `else if`, but who knows, maybe I messed up in yet another way.

**Comment by Stanzilla** [comment]
Yup, that worked, thanks :)

**Comment by LBBO** [comment]
Great! I probably won't be able to publish the fix until this evening, but everyone interested enough has the necessary code here anyway.
