### ISSUE TITLE
bin script published with DOS line endings

### ISSUE THREAD

**Issue by derelk** [genderquery/netflix-migrate#3]
I really appreciate the update, but it looks like `0.0.3` was published such that the bin script has DOS line endings and doesn't run in OS X (and presumably all *nix environments):
```
env: node\r: No such file or directory
```

Looks to be a known problem with publishing to npm: npm/npm#12371. This is a regression from `0.0.1` and `0.0.2`.

**Comment by genderquery** [comment]
Finally fixed by just publishing from Debian.
