### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by cyril4j** [genderquery/netflix-migrate#4]
I'm unable to run the script to export my ratings and get the error below. Any idea?

$ netflix-migrate --email <my-email> --profile <my-profile> --export ratings.json                                                                                                                                    
Password: 

evalmachine.<anonymous>:1
(function () { var request = new XMLHttpRequest(); request.open('GET', '/ichnaea/cl2/freeform/WebsiteDetect?source=wwwhead&fetchType=js&modalView=login', true); request.send(); var request2 = new XMLHttpRequest(); request2.open('GET', '/ichnaea/cl2/freeform/WebsiteScreen?source=wwwhead&fetchType=js' + '&winw=' + window.outerWidth + '&winh=' + window.outerHeight + '&screenw=' + window.innerWidth + '&screenh=' + window.innerHeight + '&ratio=' + ( window.devicePixelRatio ? window.devicePixelRatio : 'unsupported' ), true); request2.send(); })();
                                 ^
ReferenceError: XMLHttpRequest is not defined
    at evalmachine.<anonymous>:1:34
    at evalmachine.<anonymous>:1:545
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Object.exports.runInContext (vm.js:67:17)
    at Object.<anonymous> (/usr/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:272:12)
    at /usr/lib/node_modules/netflix-migrate/node_modules/cheerio/lib/api/traversing.js:300:18
    at /usr/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:935:11
    at /usr/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:4920:15
    at baseReduce (/usr/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:932:5)
    at Function.reduce (/usr/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:9698:14)

**Comment by genderquery** [comment]
I am only able to reproduce with an invalid login. Make sure you are putting your credentials after those options:
`$ netflix-migrate --email cyril4j@example.com --profile Cyril --export ratings.json`

I'll have to add some code to make bad logins more graceful.

**Comment by cyril4j** [comment]
That was it indeed. Thanks!
