### ISSUE TITLE
401 Unauthorized when attempting to import a profile

### ISSUE THREAD

**Issue by nemtsov** [genderquery/netflix-migrate#5]
When I attempt to import with the correct password, I get:

```
HttpError { name: 'HttpError', message: '401: Unauthorized' }
```

Incorrect password returns:

```
evalmachine.<anonymous>:1
(function () { var request = new XMLHttpRequest(); request.open('...
```

Here's the command I'm running:

```
netflix-migrate --email '<my_gmail>' --profile '<my_second_profile>' --import ratings.json
```

The export worked as designed.

**Comment by dictvm** [comment]
Happens here as well.

**Comment by LukeDurrant** [comment]
I just created a PR that fixes this issue
https://github.com/genderquery/node-netflix2/pull/5

**Comment by genderquery** [comment]
Thanks @LukeDurrant !
