### ISSUE TITLE
When I try to import I receive a message 401: Unauthorized 

### ISSUE THREAD

**Issue by JG24** [genderquery/netflix-migrate#6]
I have 2 profiles. On one profile import works, the other does not. I receive a message:
```
user@server:# netflix-migrate --email email@addres --profile Example --import netflix-Example.json
Password:
Importing NameOfTheTvShow
HttpError { name: 'HttpError', message: '401: Unauthorized' }
```
Both profiles in the name have plaintext, no spaces.

**Comment by holman** [comment]
I'm getting the same too on my import; maybe something changed on Netflix's end recently?

**Comment by pDetmer** [comment]
Same here, but it also doesn't work with the main profile. Even though it says 'Import complete', the list is empty.

**Comment by awesomeness801** [comment]
I am also having this problem. This was apparently fixed in issue 5, but it isn't. maybe a similar change is necessary?

**Comment by genderquery** [comment]
Try latest version 0.0.7.
