### ISSUE TITLE
ReferenceError: document is not defined   (Node v10.7.0)

### ISSUE THREAD

**Issue by cephalopodsquid** [genderquery/netflix-migrate#8]
evalmachine.<anonymous>:3
(function(undefined) {!function(e){var t=Object.prototype.hasOwnProperty("__defineGetter__"),r="A property cannot both have accessors and be writable or have a value";Object.defineProperty=function(n,o,i){if(e&&(n===window||n===document||n===Element.prototype||n instanceof Element))return e(n,o,i);if(null===n||!(n instanceof Object||"object"==typeof n))throw new TypeError("Object.defineProperty called on non-object");if(!(i instanceof Object))throw new TypeError("Property description must be an object");var c=String(o),a="value"in i||"writable"in i,f="get"in i&&typeof i.get,p="set"in i&&typeof i.set;if(f){if("function"!==f)throw new TypeError("Getter must be a function");if(!t)throw new TypeError("Getters & setters cannot be defined on this javascript engine");if(a)throw new TypeError(r);Object.__defineGetter__.call(n,c,i.get)}else n[c]=i.value;if(p){if("function"!==p)throw new TypeError("Setter must be a function");if(!t)throw new TypeError("Getters & setters cannot be defined on 

ReferenceError: document is not defined
    at Function.Object.defineProperty (evalmachine.<anonymous>:3:229)
    at Object.<anonymous> (evalmachine.<anonymous>:3:1158)
    at evalmachine.<anonymous>:7:7838
    at Script.runInContext (vm.js:102:20)
    at Object.runInContext (vm.js:280:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:272:12)
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/cheerio/lib/api/traversing.js:300:18
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:914:11
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:4901:15
    at baseReduce (/usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:911:5)

**Comment by genderquery** [comment]
Should be fixed as of version 0.0.7.
